-- 1. Create Gallery Table
CREATE TABLE gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  url TEXT NOT NULL
);

-- 2. Create Toppers Table
CREATE TABLE toppers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  score TEXT NOT NULL,
  image TEXT NOT NULL
);

-- 3. Create Notices Table
CREATE TABLE notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  date DATE DEFAULT CURRENT_DATE NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL
);

-- 4. Create Quick Links Table
CREATE TABLE quick_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  label TEXT NOT NULL,
  url TEXT NOT NULL
);

-- Note: Ensure you create a public bucket named "assets" in Supabase Storage.
-- Enable public read access for the "assets" bucket.
-- You may need to disable RLS or add policies to allow service_role/anon access for demo purposes.
